# Site info
title: bhansconnect
author: ""
email: brendan.hansknecht@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Just the ramblings of a software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bhansconnect.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bhansconnect
github_username:  bhansconnect

# Site settings
permalink: /:title/
markdown: kramdown
date_format: "%b %-d, %Y"
# paginate: 5
# paginate_path: "/:num/"
# show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
